# Jupyter Notebook - Week 5, Book 1
## Basic ndarrays
### Task 1
Create an ndarray based on the following list:
```python
data = [43, 23, 65, 23, 56, 989, 23, 54, 54]
```
Then print the whole array, its size, shape, and its dimensionality on separate lines.

In [1]:
import numpy as np

data = [43, 23, 65, 23, 56, 989, 23, 54, 54]
data_array = np.array(data)

print(data)
print(data_array)

print(data_array.size)
print(data_array.ndim)
print(data_array.shape)

[43, 23, 65, 23, 56, 989, 23, 54, 54]
[ 43  23  65  23  56 989  23  54  54]
9
1
(9,)


### Task 2
Now print the same data for an ndarray based on the following lists:
```python
data2 = [[343.2232, 123424.323], [78343, 32, 4, 321, 739], [7823, 687, 725, 109, 23]]
```

In [2]:
import numpy as np

data2 = [[343.2232, 123424.323], [78343, 32, 4, 321, 739], [7823, 687, 725, 109, 23]]
data2_array = np.array(data2)

print(data2)
print(data2_array)

print(data2_array.size)
print(data2_array.ndim)
print(data2_array.shape)

[[343.2232, 123424.323], [78343, 32, 4, 321, 739], [7823, 687, 725, 109, 23]]
[list([343.2232, 123424.323]) list([78343, 32, 4, 321, 739])
 list([7823, 687, 725, 109, 23])]
3
1
(3,)


### Task 3
Finally, print the data for an ndarry based on the following:
```python
data3 = [[62, 74, 99, 90, 11], [78343, 32, 4, 321, 739], [7823, 687, 725, 109, 23]]
```

In [3]:
import numpy as np

data3 = [[63, 74, 99, 90, 11], [78343, 32, 4, 321, 739], [7823, 687, 725, 109, 23]]
data3_array = np.array(data3)

print(data3)
print(data3_array)

print(data3_array.size)
print(data3_array.ndim)
print(data3_array.shape)

[[63, 74, 99, 90, 11], [78343, 32, 4, 321, 739], [7823, 687, 725, 109, 23]]
[[   63    74    99    90    11]
 [78343    32     4   321   739]
 [ 7823   687   725   109    23]]
15
2
(3, 5)


Notice the difference in how numpy treats the lists in tasks 2 and 3. 