# Jupyter Notebook - Week 5, Book 2
## Indexing ndarrays

Like lists, we use [*index*] to access a specific element of an ndarray. In many cases that 'element' will actually be a subarray of the ndarray, so it will be iterable as well.

### Task 1
Create an ndarray based on the following lists:
```python
data3 = [[62, 74, 99, 90, 11], [78343, 32, 4, 321, 739], [7823, 687, 725, 109, 23]]
```
And write code to iterate over the ndarray, printing it using the following format:

```python
Row 1
62
74
99
90
11

Row 2
78343
32
4
321
739

Row 3
7823
687
725
109
23
```

In [1]:
import numpy as np

data3 = [[62, 74, 99, 90, 11], [78343, 32, 4, 321, 739], [7823, 687, 725, 109, 23]]
array = np.array(data3)

i = 1
for row in array:
    print("Row {}".format(i))
    for element in row:
        print(element)
    print()
    i += 1

Row 1
62
74
99
90
11

Row 2
78343
32
4
321
739

Row 3
7823
687
725
109
23



### Task 2
Now take the ndarray you created above and print *only* the second row.

In [26]:
import numpy as np

data3 = [[62, 74, 99, 90, 11], [78343, 32, 4, 321, 739], [7823, 687, 725, 109, 23]]
array = np.array(data3)

row = 2
print("Row {}".format(row))
print(array[-row])

Row 2
[78343    32     4   321   739]


## Slicing lists
We can create a 'view' of a list by using ':' to slice up the ndarray the way we can a string or list.

### Task 3
Take the following ndarray and make a slice containing the third and fourth rows. Display both of them, using a simple print().

```python
full_data = np.array([[14, 344, 23, 51], [95, 54, 103, 1], [34, 23, 11, 89], [876, 482, 962]])
```

In [19]:
import numpy as np

full_data = np.array([[14, 344, 23, 51], [95, 54, 103, 1], [34, 23, 11, 89], [876, 482, 962, 55]])

print(full_data[-2:,])

[[ 34  23  11  89]
 [876 482 962  55]]
