# Jupyter Notebook - Week 5, Book 4
## Vectorized Operations
### Task 1
Take the following code which creates a randomly filled 5 by 3 ndarray:
```python
final_data = np.random.randint(0, 1000, (5, 3))
```
After using this to create the ndarray, print the following things to the screen:
- the ndarray
- the ndarray multiplied by 5
- the ndarray with 100 added to each element

In [2]:
import numpy as np

final_data = np.random.randint(0,1000,(5,3))

print(final_data)
print(final_data * 5)
print(final_data + 100)

[[982 339 869]
 [443 390 967]
 [685 715 299]
 [  6 159 989]
 [496 584  63]]
[[4910 1695 4345]
 [2215 1950 4835]
 [3425 3575 1495]
 [  30  795 4945]
 [2480 2920  315]]
[[1082  439  969]
 [ 543  490 1067]
 [ 785  815  399]
 [ 106  259 1089]
 [ 596  684  163]]


## Conditional Array Operations
### Task 2
Using the *where* operation shown in your notes, take your program above and produce an ndarray where every value less than 100 is set to zero.
Print the original array, then the modified array, to show this in action.

In [3]:
modified_data = np.where(final_data < 100, 0, final_data)

print(final_data)
print(modified_data)

[[982 339 869]
 [443 390 967]
 [685 715 299]
 [  6 159 989]
 [496 584  63]]
[[982 339 869]
 [443 390 967]
 [685 715 299]
 [  0 159 989]
 [496 584   0]]
