# Jupyter Notebook - Week 5, Book 3
## Boolean Indexing
### Task 1
Let's start with the examples in the notes.
Take the following 2-dimensional array:
```python
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```
And the following array, which we are using as an index:
```python
names = np.array(["Alan", "Jane", "Jesse"])
```
Now use boolean indexing to extract the elements of *arr2d* which are linked to 'Jane', and print them on separate lines.
Your result should look like:
```python
4
5
6
```
Remember that the result of boolean indexing could be the same dimensionality as the original ndarray, so you will have to handle lists within list (using loops within loops)

In [8]:
import numpy as np

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
names = np.array(["Alan", "Jane", "Jesse"])

for lines in arr2d[names == "Jane"]:
    for elements in lines:
        print(elements)

4
5
6


### Task 2
Now lets reverse the above program. Instead of listing all elements aligned with 'Jane', I now want all elements aligned with either 'Alan' or 'Jesse'.

Print each row on its own line, as shown below:
```python
[1, 2, 3]
[7, 8, 9]
```

In [6]:
for lines in arr2d[(names == "Alan") | (names == "Jesse")]:
    print(lines)

[1 2 3]
[7 8 9]


## Fancy Indexing
Instead of using a Boolean array as an index (as above) we can use a list of integers, which will be used as indicies. This allows us to select specific dimensions of an ndarray, in a specific order.

For example:
```python
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[[3,1,2]])
```
would print:
```
[[7 8 9]
 [1 2 3]
 [4 5 6]]
 ```
 
### Task 3
Create an ndarray containing 5 rows, each of which has 3 random numbers within. (Have a loop that runs 3 times, inside a loop running 5 times.) Print the ndarray using a single print statement, and then print the third, second, and fourth rows in order.

In [3]:
import random as r
import numpy as np

## easy way
#array = np.random.randint(0,1000,(5,3))

## list comprehension
#[[output_expression() for(set of columns to iterate)] for (set of rows to iterate)]
#list_of_lists = [[r.randint(0,100) for col in range(3)] for row in range(5)]
#print(list_of_lists)
#array = np.array(list_of_lists)
#print(array)

#looping
list_of_lists = []
for row in range(5):
    list_of_lists.append([])
    for col in range(3):
        list_of_lists[row].append(r.randint(1,100))

array = np.array(list_of_lists)
print(array)

array[[2,1,3]]

[[ 81  67   8]
 [ 63  78  46]
 [ 67  64  21]
 [ 80   8  80]
 [100  73  37]]


array([[67, 64, 21],
       [63, 78, 46],
       [80,  8, 80]])