# Jupyter Notebook - Week 5, Book 3
## Boolean Indexing
### Task 1
Let's start with the examples in the notes.
Take the following 2-dimensional array:
```python
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```
And the following array, which we are using as an index:
```python
names = np.array(["Alan", "Jane", "Jesse"])
```
Now use boolean indexing to extract the elements of *arr2d* which are linked to 'Jane', and print them on separate lines.
Your result should look like:
```python
4
5
6
```
Remember that the result of boolean indexing could be the same dimensionality as the original ndarray, so you will have to handle lists within list (using loops within loops)

In [1]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
names = np.array(["Alan", "Jane", "Jesse"])

for row in arr2d[names == 'Jane']:
    print(row)

[4 5 6]


### Task 2
Now lets reverse the above program. Instead of listing all elements aligned with 'Jane', I now want all elements aligned with either 'Alan' or 'Jesse'.

Print each row on its own line, as shown below:
```python
[1, 2, 3]
[7, 8, 9]
```

In [2]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
names = np.array(["Alan", "Jane", "Jesse"])

for row in arr2d[(names == 'Alan') | (names == 'Jesse')]:
    print(row)

[1 2 3]
[7 8 9]


## Fancy Indexing
Instead of using a Boolean array as an index (as above) we can use a list of integers, which will be used as indicies. This allows us to select specific dimensions of an ndarray, in a specific order.

For example:
```python
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[[3,1,2]])
```
would print:
```
[[7 8 9]
 [1 2 3]
 [4 5 6]]
 ```
 
### Task 3
Create an ndarray containing 5 rows, each of which has 3 random numbers within. Print the ndarray using a single print statement, and then print the third, second, and fourth rows in order.

In [5]:
arr2d = np.random.rand(5, 3)
print(arr2d)
print(arr2d[[2, 1, 3]])

[[0.13256554 0.55148216 0.02388311]
 [0.59568898 0.48588534 0.12460292]
 [0.66335599 0.31769732 0.10340956]
 [0.0783189  0.98022678 0.70852065]
 [0.11568323 0.95397754 0.5027199 ]]
[[0.66335599 0.31769732 0.10340956]
 [0.59568898 0.48588534 0.12460292]
 [0.0783189  0.98022678 0.70852065]]
