# Jupyter Notebook - Week 5, Book 4
## Vectorized Operations
### Task 1
Take the following code which creates a randomly filled 5 by 3 ndarray:
```python
final_data = np.random.randint(0, 1000, (5, 3))
```
After using this to create the ndarray, print the following things to the screen:
- the ndarray
- the ndarray multiplied by 5
- the ndarray with 100 added to each element

In [1]:
import numpy as np
final_data = np.random.randint(0, 1000, (5, 3))

print(final_data)
print(final_data * 5)
print(final_data + 100)

[[ 40 262 954]
 [908 334   6]
 [340 763 892]
 [422 401 423]
 [972 375 316]]
[[ 200 1310 4770]
 [4540 1670   30]
 [1700 3815 4460]
 [2110 2005 2115]
 [4860 1875 1580]]
[[ 140  362 1054]
 [1008  434  106]
 [ 440  863  992]
 [ 522  501  523]
 [1072  475  416]]


## Conditional Array Operations
### Task 2
Using the *where* operation shown in your notes, take your program above and produce an ndarray where every value less than 100 is set to zero.
Print the original array, then the modified array, to show this in action.

In [18]:
import numpy as np
final_data = np.random.randint(0, 1000, (5, 3))

print(final_data)
arr2d = np.where(final_data < 100, 0, final_data)
print(arr2d)

[[548  76 923]
 [428 632 550]
 [580 741 654]
 [570  33  36]
 [885 197 365]]
[[548   0 923]
 [428 632 550]
 [580 741 654]
 [570   0   0]
 [885 197 365]]
