# Jupyter Notebook - Week 5, Book 1
## Basic ndarrays
### Task 1
Create an ndarray based on the following list:
```python
data = [43, 23, 65, 23, 56, 989, 23, 54, 54]
```
Then print the whole array, its size, shape, and its dimensionality on separate lines.

In [1]:
import numpy as np
data = [43, 23, 65, 23, 56, 989, 23, 54, 54]
array = np.array(data)
print(array)
print(array.size)
print(array.shape)
print(array.ndim)

[ 43  23  65  23  56 989  23  54  54]
9
(9,)
1


### Task 2
Now print the same data for an ndarray based on the following lists:
```python
data2 = [[343.2232, 123424.323], [78343, 32, 4, 321, 739], [7823, 687, 725, 109, 23]]
```

In [3]:
import numpy as np
data2 = [[343.2232, 123424.323], [78343, 32, 4, 321, 739], [7823, 687, 725, 109, 23]]
array = np.array(data2)
print(array)
print(array.size)
print(array.shape)
print(array.ndim)

[list([343.2232, 123424.323]) list([78343, 32, 4, 321, 739])
 list([7823, 687, 725, 109, 23])]
3
(3,)
1


### Task 3
Finally, print the data for an ndarry based on the following:
```python
data3 = [[62, 74, 99, 90, 11], [78343, 32, 4, 321, 739], [7823, 687, 725, 109, 23]]
```

In [2]:
import numpy as np
data3 = [[62, 74, 99, 90, 11], [78343, 32, 4, 321, 739], [7823, 687, 725, 109, 23]]
array = np.array(data3)
print(array)
print(array.size)
print(array.shape)
print(array.ndim)

[[   62    74    99    90    11]
 [78343    32     4   321   739]
 [ 7823   687   725   109    23]]
15
(3, 5)
2


Notice the difference in how numpy treats the lists in tasks 2 and 3. 